### ISSUE TITLE
Can't use GE Kitchen Hub as notification receiver

### ISSUE THREAD

**Issue by ggiesen** [smrtprjcts/atvnotif#1]
I'm currently using Notifications for Android TV to send notifications (mostly phone calls) to my Sony TV and GE Kitchen Hub. Due to Google Play restrictions, it no longer sends Caller ID. I'm trying out Android TV Notifier (and I like the fact it will have Tasker integration), but due to the fact my GE Kitchen Hub appears as a tablet and not a TV, I can't set it up as a notification receiver.

Would it be possible to create a setting that allows you to specify a non-TV device as a receiver?

FYI  using the Google Play version on my TV and Kitchen Hub, and the GitHub release on my phone.

**Comment by smrtprjcts** [comment]
Hi,

_Would it be possible to create a setting that allows you to specify a non-TV device as a receiver?_
Of course, I can do it, but I need some info for that. Please send an e-mail to smrtprjcts+atvnotif@gmail.com.
The process will be faster if you can send the device product properties in the first mail ;)
With adb:
These would be the
adb shell getprop ro.product.manufacturer
adb shell getprop ro.product.model
adb shell getprop ro.product.device
adb shell getprop ro.product.name
but the better is the whole list with adb shell getprop

If you cannot send it we will solve it another way ;)
Thanks a lot.

_FYI using the Google Play version on my TV and Kitchen Hub, and the GitHub release on my phone._
It's ok, there isn't any advantage of the Github version on TVs! But should be the same version (vx.y.z) for compatibility.

**Comment by smrtprjcts** [comment]
Please try it on the Kitchen Hub
https://drive.google.com/file/d/1EAmSUDBRuC1jNzW1TU4Ciax2fiJDufGR/view?usp=sharing

**Comment by ggiesen** [comment]
So that release you provided solved my issue with two caveats:

1. There's a grey band at the top of the screen that cuts off a small part of the QR code (I was able to pair regardless)

2. I can only pair one device at a time. With Notifications for Android TV, I could send notifications to multiple devices (and from multiple devices). I expect to end up with 3-4 source devices, and 4-5 target devices.

I tried to see if I could access the device with ADB. I was able to enable the developer options, but unfortunately the device doesn't support adb over network and doesn't have any user-accessible) USB ports.

**Comment by ggiesen** [comment]
So that release you provided solved my issue with two caveats:

1. There's a grey band at the top of the screen that cuts off a small part of the QR code (I was able to pair regardless)

2. I can only pair one device at a time. With Notifications for Android TV, I could send notifications to multiple devices (and from multiple devices). I expect to end up with 3-4 source devices, and 4-5 target devices.

I tried to see if I could access the device with ADB. I was able to enable the developer options, but unfortunately the device doesn't support adb over network and doesn't have any user-accessible) USB ports.

FYI I'm only using the GitHub version on my phone (so it can read CID). I'm using the Google Play version on my TV, and the custom version you supplied on my Kitchen Hub

**Comment by ggiesen** [comment]
Screenshot for your reference (I've blurred out the IP address and most of the QR code):

![20230804_095524.jpg](https://github.com/smrtprjcts/atvnotif/assets/5194146/00a68576-cba3-4b39-8b26-b07e4e3e4481)

**Comment by smrtprjcts** [comment]
Nice, I will add a small padding to the top and the QR will be on a better place. Thanks for the picture.

I'd like to solve the multi device connection in the (I hope near) future but I'd like to add some other simplier features to the app before.
Please be patient. :)

**Comment by smrtprjcts** [comment]
@ggiesen if you have any idea what is the grey band...? Is it only in my app?

**Comment by ggiesen** [comment]
> @ggiesen if you have any idea what is the grey band...? Is it only in my app?

Yes, it is only in your app.

**Comment by smrtprjcts** [comment]
v0.5.2 already supports this device.
Grey band is not fixed yet, I think the padding is not the the best solution, we should figure out what the reason is

**Comment by smrtprjcts** [comment]
Hi @ggiesen ,
please send a (empty) mail to me (smrtprjcts+atvnotif@gmail.com), I'd like to share a special apk, built for you.
Thanks
