### ISSUE TITLE
No reply from support email

### ISSUE THREAD

**Issue by gpion** [smrtprjcts/atvnotif#4]
Email send  to smrtprjcts+atvnotif@gmail.com got no answer (send on nov 2023)

**Comment by smrtprjcts** [comment]
I did not get a mail on that day but smrtprjcts+atvnotif@gmail.com

**Comment by gpion** [comment]
screenshot of my gmail history
![image](https://github.com/smrtprjcts/atvnotif/assets/2971216/3f3cb733-42eb-4b7b-9e81-53eccf82d5b4)
I've send two emails to that address that day
